---
component_skel:
  apm-server:
    belongs_to:
      - elk_all
      - apm_all
  elastic-logstash:
    belongs_to:
      - elk_all
      - elasticsearch
      - elasticsearch_all
      - logstash
      - logstash_all
  kibana:
    belongs_to:
      - elk_all

container_skel:
  apm-server_container:
    belongs_to:
      - log_containers
    contains:
      - apm-server
  elastic-logstash_container:
    belongs_to:
      - log_containers
    contains:
      - elastic-logstash
      - kibana
