---
## Usage create a set of variables that the tools team will use for our deployments.
## This will create
##   - proxy environment options options when "http_proxy_server" is defined. The no proxy configuration is optional.
##   - haproxy configurations for our internal tooling
##   - beat service state options
##
## Playbook options:
##  - "http_proxy_server" (OPTIONAL)
##  - "https_proxy_server" (OPTIONAL)
##  - "extra_no_proxy_hosts" (OPTIONAL)
##  - "java_http_proxy" (OPTIONAL)
##  - "java_https_proxy_port" (OPTIONAL)
##  - "java_https_proxy" (OPTIONAL)
##  - "java_https_proxy_port" (OPTIONAL)
##  - "var_location" (OPTIONAL) variable directory path
##  - "file_location" (OPTIONAL) variable file path
##
## When defining a proxy, the http(s)_proxy_server variables must be in the form of a URL with a specified port.

# USAGE:$ (openstack-ansible || ansible-playbook) generate-environment-vars.yml -e 'http_proxy_server=https://proxy_server.local:3128'

- name: Create user tools variables file
  hosts: localhost
  connection: local
  user: root
  gather_facts: no
  vars:
    http_proxy_server: "none://none:none"
    java_http_proxy: "{{ (http_proxy_server).split(':')[1].strip('/') }}"
    java_https_proxy: "{{ (https_proxy_server | default(http_proxy_server)).split(':')[1].strip('/') }}"
    java_http_proxy_port: "{{ (http_proxy_server).split(':')[2].strip('/') }}"
    java_https_proxy_port: "{{ (https_proxy_server | default(http_proxy_server)).split(':')[2].strip('/') }}"
    no_proxy_hosts:
      - localhost
      - 127.0.0.1
      - "{{ (groups['rabbitmq_all'] | union(groups['log_containers'] )) | map('extract', hostvars, 'ansible_host') | list | join(',') }}"

  tasks:
    - name: Ensure openstack-deploy directory exists
      file:
        path: "{{ var_location | default('/etc/openstack_deploy') }}"
        state: directory

    - name: Create user_tools_variables.yml
      template:
        src: templates/user_tools_variables.yml.j2
        dest: "{{ file_location | default(var_location + '/user_tools_variables.yml') }}"

    - name: Ensure environment files directory exists
      file:
        path: "{{ var_location | default('/etc/openstack_deploy') }}/env.d"
        state: directory

    - name: Copy environment files
      copy:
        src: 'files/{{ item }}'
        dest: "{{ var_location }}/env.d/{{ item }}"
      with_items:
        - elk.yml
        - fleet.yml

    - name: Find log_hosts entries
      find:
        paths: /etc/openstack_deploy
        file_type: file
        contains: "^log_hosts:.*"
        patterns: "*.yml"
        recurse: yes
      register: log_hosts_entries

    - name: Add kolide_hosts entries
      lineinfile:
        path: "{{ item.path }}"
        line: 'kolide_hosts: *log_hosts'
      with_items: "{{ log_hosts_entries.files }}"
